import sqlite3
import json
from pathlib import Path

def create_messier_database():
    """Create and populate the Messier Catalogue database"""
    
    db_path = Path(__file__).parent / "messier.db"
    conn = sqlite3.connect(db_path)
    cursor = conn.cursor()
    
    # Create table
    cursor.execute("""
        CREATE TABLE IF NOT EXISTS messier_objects (
            id TEXT PRIMARY KEY,
            messier_number INTEGER,
            ngc_id TEXT,
            name TEXT,
            type TEXT,
            ra_hours REAL,
            dec_degrees REAL,
            magnitude REAL,
            size_arcmin REAL,
            constellation TEXT,
            best_months TEXT,
            min_aperture_mm INTEGER,
            difficulty TEXT,
            description TEXT,
            imaging_notes TEXT,
            distance_ly REAL,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )
    """)
    
    # Sample data for top 10 beginner-friendly objects
    sample_objects = [
        {
            "id": "M31",
            "messier_number": 31,
            "ngc_id": "NGC 224",
            "name": "Andromeda Galaxy",
            "type": "galaxy",
            "ra_hours": 0.712,
            "dec_degrees": 41.269,
            "magnitude": 3.4,
            "size_arcmin": 178.0,
            "constellation": "Andromeda",
            "best_months": json.dumps(["Sep", "Oct", "Nov", "Dec"]),
            "min_aperture_mm": 50,
            "difficulty": "easy",
            "description": "The nearest major galaxy to the Milky Way, visible to the naked eye",
            "imaging_notes": "Wide field recommended. Long exposures reveal spiral structure.",
            "distance_ly": 2537000
        },
        {
            "id": "M42",
            "messier_number": 42,
            "ngc_id": "NGC 1976",
            "name": "Orion Nebula",
            "type": "nebula",
            "ra_hours": 5.583,
            "dec_degrees": -5.391,
            "magnitude": 4.0,
            "size_arcmin": 65.0,
            "constellation": "Orion",
            "best_months": json.dumps(["Dec", "Jan", "Feb", "Mar"]),
            "min_aperture_mm": 50,
            "difficulty": "easy",
            "description": "Stunning emission nebula in Orion's sword, great for beginners",
            "imaging_notes": "Very bright. Watch for overexposure in core. Beautiful colors.",
            "distance_ly": 1344
        },
        {
            "id": "M45",
            "messier_number": 45,
            "ngc_id": None,
            "name": "Pleiades",
            "type": "open_cluster",
            "ra_hours": 3.783,
            "dec_degrees": 24.117,
            "magnitude": 1.6,
            "size_arcmin": 110.0,
            "constellation": "Taurus",
            "best_months": json.dumps(["Nov", "Dec", "Jan", "Feb"]),
            "min_aperture_mm": 30,
            "difficulty": "easy",
            "description": "Beautiful open star cluster, also known as the Seven Sisters",
            "imaging_notes": "Wide field essential. Blue reflection nebulae visible with long exposures.",
            "distance_ly": 444
        },
        {
            "id": "M13",
            "messier_number": 13,
            "ngc_id": "NGC 6205",
            "name": "Hercules Globular Cluster",
            "type": "globular_cluster",
            "ra_hours": 16.694,
            "dec_degrees": 36.461,
            "magnitude": 5.8,
            "size_arcmin": 20.0,
            "constellation": "Hercules",
            "best_months": json.dumps(["May", "Jun", "Jul", "Aug"]),
            "min_aperture_mm": 100,
            "difficulty": "moderate",
            "description": "Brightest globular cluster in northern hemisphere",
            "imaging_notes": "Dense core requires careful exposure. Resolve individual stars.",
            "distance_ly": 25100
        },
        {
            "id": "M27",
            "messier_number": 27,
            "ngc_id": "NGC 6853",
            "name": "Dumbbell Nebula",
            "type": "planetary_nebula",
            "ra_hours": 19.992,
            "dec_degrees": 22.721,
            "magnitude": 7.5,
            "size_arcmin": 8.0,
            "constellation": "Vulpecula",
            "best_months": json.dumps(["Jul", "Aug", "Sep", "Oct"]),
            "min_aperture_mm": 100,
            "difficulty": "moderate",
            "description": "Bright planetary nebula with distinctive dumbbell shape",
            "imaging_notes": "OIII and H-alpha filters enhance detail. Good narrowband target.",
            "distance_ly": 1360
        },
        {
            "id": "M51",
            "messier_number": 51,
            "ngc_id": "NGC 5194",
            "name": "Whirlpool Galaxy",
            "type": "galaxy",
            "ra_hours": 13.497,
            "dec_degrees": 47.195,
            "magnitude": 8.4,
            "size_arcmin": 11.0,
            "constellation": "Canes Venatici",
            "best_months": json.dumps(["Apr", "May", "Jun", "Jul"]),
            "min_aperture_mm": 150,
            "difficulty": "moderate",
            "description": "Face-on spiral galaxy with prominent spiral arms",
            "imaging_notes": "Companion galaxy NGC 5195 visible. Long exposures reveal spiral structure.",
            "distance_ly": 23000000
        },
        {
            "id": "M57",
            "messier_number": 57,
            "ngc_id": "NGC 6720",
            "name": "Ring Nebula",
            "type": "planetary_nebula",
            "ra_hours": 18.887,
            "dec_degrees": 33.029,
            "magnitude": 8.8,
            "size_arcmin": 1.4,
            "constellation": "Lyra",
            "best_months": json.dumps(["Jun", "Jul", "Aug", "Sep"]),
            "min_aperture_mm": 100,
            "difficulty": "moderate",
            "description": "Famous ring-shaped planetary nebula",
            "imaging_notes": "Small but bright. OIII filter recommended. Central star visible with long exposures.",
            "distance_ly": 2300
        },
        {
            "id": "M81",
            "messier_number": 81,
            "ngc_id": "NGC 3031",
            "name": "Bode's Galaxy",
            "type": "galaxy",
            "ra_hours": 9.927,
            "dec_degrees": 69.065,
            "magnitude": 6.9,
            "size_arcmin": 26.9,
            "constellation": "Ursa Major",
            "best_months": json.dumps(["Feb", "Mar", "Apr", "May"]),
            "min_aperture_mm": 100,
            "difficulty": "moderate",
            "description": "Bright spiral galaxy, often imaged with M82",
            "imaging_notes": "Wide field to include M82. Beautiful spiral structure.",
            "distance_ly": 11800000
        },
        {
            "id": "M104",
            "messier_number": 104,
            "ngc_id": "NGC 4594",
            "name": "Sombrero Galaxy",
            "type": "galaxy",
            "ra_hours": 12.666,
            "dec_degrees": -11.623,
            "magnitude": 8.0,
            "size_arcmin": 8.7,
            "constellation": "Virgo",
            "best_months": json.dumps(["Mar", "Apr", "May", "Jun"]),
            "min_aperture_mm": 150,
            "difficulty": "challenging",
            "description": "Edge-on spiral galaxy with prominent dust lane",
            "imaging_notes": "Distinctive sombrero shape. Requires good seeing conditions.",
            "distance_ly": 29000000
        },
        {
            "id": "M1",
            "messier_number": 1,
            "ngc_id": "NGC 1952",
            "name": "Crab Nebula",
            "type": "supernova_remnant",
            "ra_hours": 5.575,
            "dec_degrees": 22.017,
            "magnitude": 8.4,
            "size_arcmin": 6.0,
            "constellation": "Taurus",
            "best_months": json.dumps(["Nov", "Dec", "Jan", "Feb"]),
            "min_aperture_mm": 150,
            "difficulty": "challenging",
            "description": "Supernova remnant with intricate filamentary structure",
            "imaging_notes": "Narrowband imaging reveals incredible detail. OIII and H-alpha recommended.",
            "distance_ly": 6500
        },
        {
            "id": "M8",
            "messier_number": 8,
            "ngc_id": "NGC 6523",
            "name": "Lagoon Nebula",
            "type": "nebula",
            "ra_hours": 18.062,
            "dec_degrees": -24.383,
            "magnitude": 6.0,
            "size_arcmin": 90.0,
            "constellation": "Sagittarius",
            "best_months": json.dumps(["Jun", "Jul", "Aug", "Sep"]),
            "min_aperture_mm": 50,
            "difficulty": "easy",
            "description": "Large, bright emission nebula with dark dust lanes",
            "imaging_notes": "Excellent summer target. Wide field captures surrounding nebulosity.",
            "distance_ly": 5200
        },
        {
            "id": "M20",
            "messier_number": 20,
            "ngc_id": "NGC 6514",
            "name": "Trifid Nebula",
            "type": "nebula",
            "ra_hours": 18.033,
            "dec_degrees": -23.033,
            "magnitude": 6.3,
            "size_arcmin": 28.0,
            "constellation": "Sagittarius",
            "best_months": json.dumps(["Jun", "Jul", "Aug", "Sep"]),
            "min_aperture_mm": 100,
            "difficulty": "moderate",
            "description": "Emission nebula divided by dark dust lanes",
            "imaging_notes": "Beautiful three-lobed structure. Often imaged with M8.",
            "distance_ly": 5200
        },
        {
            "id": "M33",
            "messier_number": 33,
            "ngc_id": "NGC 598",
            "name": "Triangulum Galaxy",
            "type": "galaxy",
            "ra_hours": 1.564,
            "dec_degrees": 30.660,
            "magnitude": 5.7,
            "size_arcmin": 73.0,
            "constellation": "Triangulum",
            "best_months": json.dumps(["Oct", "Nov", "Dec", "Jan"]),
            "min_aperture_mm": 100,
            "difficulty": "moderate",
            "description": "Face-on spiral galaxy, third largest in Local Group",
            "imaging_notes": "Large and diffuse. Wide field recommended. Long exposures reveal spiral arms.",
            "distance_ly": 2730000
        },
        {
            "id": "M44",
            "messier_number": 44,
            "ngc_id": None,
            "name": "Beehive Cluster",
            "type": "open_cluster",
            "ra_hours": 8.667,
            "dec_degrees": 19.983,
            "magnitude": 3.7,
            "size_arcmin": 95.0,
            "constellation": "Cancer",
            "best_months": json.dumps(["Feb", "Mar", "Apr", "May"]),
            "min_aperture_mm": 30,
            "difficulty": "easy",
            "description": "Large, bright open cluster visible to naked eye",
            "imaging_notes": "Wide field essential. Beautiful star colors with short exposures.",
            "distance_ly": 577
        },
        {
            "id": "M63",
            "messier_number": 63,
            "ngc_id": "NGC 5055",
            "name": "Sunflower Galaxy",
            "type": "galaxy",
            "ra_hours": 13.262,
            "dec_degrees": 42.029,
            "magnitude": 8.6,
            "size_arcmin": 12.6,
            "constellation": "Canes Venatici",
            "best_months": json.dumps(["Apr", "May", "Jun", "Jul"]),
            "min_aperture_mm": 150,
            "difficulty": "moderate",
            "description": "Spiral galaxy with patchy, flocculent spiral arms",
            "imaging_notes": "Long exposures reveal intricate spiral structure.",
            "distance_ly": 37000000
        },
        {
            "id": "M65",
            "messier_number": 65,
            "ngc_id": "NGC 3623",
            "name": "Leo Triplet Galaxy",
            "type": "galaxy",
            "ra_hours": 11.309,
            "dec_degrees": 13.093,
            "magnitude": 9.3,
            "size_arcmin": 10.0,
            "constellation": "Leo",
            "best_months": json.dumps(["Mar", "Apr", "May", "Jun"]),
            "min_aperture_mm": 150,
            "difficulty": "moderate",
            "description": "Spiral galaxy, part of the Leo Triplet with M66 and NGC 3628",
            "imaging_notes": "Wide field to capture all three galaxies. Spring favorite.",
            "distance_ly": 35000000
        },
        {
            "id": "M82",
            "messier_number": 82,
            "ngc_id": "NGC 3034",
            "name": "Cigar Galaxy",
            "type": "galaxy",
            "ra_hours": 9.928,
            "dec_degrees": 69.680,
            "magnitude": 8.4,
            "size_arcmin": 11.2,
            "constellation": "Ursa Major",
            "best_months": json.dumps(["Feb", "Mar", "Apr", "May"]),
            "min_aperture_mm": 100,
            "difficulty": "moderate",
            "description": "Starburst galaxy with prominent dust lanes",
            "imaging_notes": "Often imaged with M81. H-alpha reveals galactic wind.",
            "distance_ly": 11500000
        },
        {
            "id": "M97",
            "messier_number": 97,
            "ngc_id": "NGC 3587",
            "name": "Owl Nebula",
            "type": "planetary_nebula",
            "ra_hours": 11.247,
            "dec_degrees": 55.017,
            "magnitude": 9.9,
            "size_arcmin": 3.4,
            "constellation": "Ursa Major",
            "best_months": json.dumps(["Feb", "Mar", "Apr", "May"]),
            "min_aperture_mm": 150,
            "difficulty": "challenging",
            "description": "Planetary nebula with two dark patches resembling owl eyes",
            "imaging_notes": "OIII filter essential. Faint but rewarding target.",
            "distance_ly": 2600
        },
        {
            "id": "M101",
            "messier_number": 101,
            "ngc_id": "NGC 5457",
            "name": "Pinwheel Galaxy",
            "type": "galaxy",
            "ra_hours": 14.054,
            "dec_degrees": 54.349,
            "magnitude": 7.9,
            "size_arcmin": 28.8,
            "constellation": "Ursa Major",
            "best_months": json.dumps(["Apr", "May", "Jun", "Jul"]),
            "min_aperture_mm": 150,
            "difficulty": "moderate",
            "description": "Face-on spiral galaxy with prominent spiral arms",
            "imaging_notes": "Large and diffuse. Long exposures reveal beautiful spiral structure.",
            "distance_ly": 21000000
        },
        {
            "id": "M106",
            "messier_number": 106,
            "ngc_id": "NGC 4258",
            "name": "NGC 4258",
            "type": "galaxy",
            "ra_hours": 12.319,
            "dec_degrees": 47.304,
            "magnitude": 8.4,
            "size_arcmin": 18.6,
            "constellation": "Canes Venatici",
            "best_months": json.dumps(["Mar", "Apr", "May", "Jun"]),
            "min_aperture_mm": 150,
            "difficulty": "moderate",
            "description": "Spiral galaxy with anomalous arms visible in H-alpha",
            "imaging_notes": "H-alpha reveals unique red emission arms. Excellent spring target.",
            "distance_ly": 23500000
        }
    ]
    
    # Insert sample data
    for obj in sample_objects:
        cursor.execute("""
            INSERT OR REPLACE INTO messier_objects 
            (id, messier_number, ngc_id, name, type, ra_hours, dec_degrees, 
             magnitude, size_arcmin, constellation, best_months, min_aperture_mm, 
             difficulty, description, imaging_notes, distance_ly)
            VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
        """, (
            obj["id"], obj["messier_number"], obj["ngc_id"], obj["name"],
            obj["type"], obj["ra_hours"], obj["dec_degrees"], obj["magnitude"],
            obj["size_arcmin"], obj["constellation"], obj["best_months"],
            obj["min_aperture_mm"], obj["difficulty"], obj["description"],
            obj["imaging_notes"], obj["distance_ly"]
        ))
    
    conn.commit()
    conn.close()
    
    print(f"✅ Database created at {db_path}")
    print(f"✅ Inserted {len(sample_objects)} sample Messier objects")

if __name__ == "__main__":
    create_messier_database()

# Made with Bob
